### PR TITLE
add `adminiuga` to users.txt

### PR DESCRIPTION
**Pull request by Adminiuga**
Fixes https://github.com/home-assistant/people/issues/46

### CODE REVIEW

**Comment by Adminiuga** [comment]
are usernames case sensitive?

**Comment by robbiet480** [comment]
Reopening, bot will close automatically in the next few days.

**Comment by robbiet480** [comment]
@Adminiuga Not case sensitive.

**Comment by robbiet480** [comment]
@Adminiuga Did you mean to close this?

**Comment by robbiet480** [comment]
Whoops, noticed you are already added, thanks

**Pull request closed without merging**
