### PR TITLE
Update users.txt

### LINKED ISSUE #69: @rohankapoorcom: Home Assistant asks you to fix your GitHub account!
Hi @rohankapoorcom - you're a member of [Home Assistant](https://github.com/home-assistant)'s organisation on GitHub, but our audit-bot has noticed your GitHub account isn't fully set up to meet the standards we need.

If you're no longer supposed to be a member of the organisation, please use your [GitHub organisation settings](https://github.com/settings/organizations) page to leave.

Otherwise, we just need you to help us with a few things to keep our code safe and secure on GitHub:

* Get a pull request opened to add your username to our [users.txt](https://github.com/home-assistant/people/blob/master/users.txt) file _- ideally, a Tech Lead or Dev Manager at Home Assistant should open this request for you_.

You have a limited amount of time to fix these issues, otherwise you'll be automatically removed from this organisation.

Thanks for helping us out - it makes our lives a lot easier, and help keeps our code secure!

### PR DESCRIPTION
**Pull request by rohankapoorcom**
Fixes #69

### CODE REVIEW

**Comment by robbiet480** [comment]
@rohankapoorcom conflict :(

**Comment by rohankapoorcom** [comment]
@robbiet480 There wasn't when I opened it :P

Should be all fixed now.

**Comment by robbiet480** [comment]
250 points to @rohankapoorcom for being third in with the PR!

**Comment by rohankapoorcom** [comment]
Something weird happened when I merged, it seems to have lost @Danielhiversen...

**Pull request merged**
